import { Reward } from '@/types/points';

export const MOCK_REWARDS: Reward[] = [
  {
    id: 'reward-001',
    title: 'Kinepolis bioscoopticket',
    description: '1 gratis bioscoopticket voor Kinepolis Gent',
    cost: 200,
    category: 'entertainment',
    terms: 'Geldig voor alle films, niet geldig op feestdagen',
  },
  {
    id: 'reward-002',
    title: '€10 Bol.com cadeaubon',
    description: 'Digitale cadeaubon voor Bol.com',
    cost: 250,
    category: 'voucher',
    terms: 'Code wordt via email verzonden',
  },
  {
    id: 'reward-003',
    title: 'Gratis koffie bij Starbucks',
    description: 'Een gratis koffie naar keuze',
    cost: 50,
    category: 'freebie',
    terms: 'Niet geldig voor specials en Frappuccinos',
  },
  {
    id: 'reward-004',
    title: '€5 Albert Heijn korting',
    description: '€5 korting op je volgende boodschappen',
    cost: 100,
    category: 'discount',
    terms: 'Minimale besteding €25',
  },
  {
    id: 'reward-005',
    title: 'Gratis parkeren Gent centrum',
    description: '2 uur gratis parkeren bij Q-Park',
    cost: 75,
    category: 'parking',
    terms: 'Geldig bij deelnemende parkeergarages',
  },
  {
    id: 'reward-006',
    title: 'Spotify Premium - 1 maand',
    description: '1 maand gratis Spotify Premium',
    cost: 180,
    category: 'entertainment',
    terms: 'Alleen voor nieuwe Spotify Premium gebruikers',
  },
  {
    id: 'reward-007',
    title: '15% korting bij Mediamarkt',
    description: 'Eenmalige korting op electronica',
    cost: 300,
    category: 'discount',
    terms: 'Niet geldig op Apple producten en aanbiedingen',
  },
  {
    id: 'reward-008',
    title: 'Gratis wafel bij Luc Wafelhuys',
    description: 'Eén gratis Gentse wafel',
    cost: 40,
    category: 'freebie',
    terms: 'Basis wafel, toppings niet inbegrepen',
  },
  {
    id: 'reward-009',
    title: 'Deliveroo korting €7,50',
    description: 'Kortingscode voor je volgende bestelling',
    cost: 150,
    category: 'food',
    terms: 'Minimale besteding €15',
  },
  {
    id: 'reward-010',
    title: 'Priority check-out toegang',
    description: 'Spring de rij over bij deelnemende winkels',
    cost: 125,
    category: 'priority',
    terms: 'Geldig 1 maand vanaf activatie',
  },
];
